Use milliseconds to display timer results
lesnitsky/perf_timer pull request #1
Opened 2019-01-27 17:38 UTC by synw

Hi. I found that the microseconds in results are not very human readable and changed this to use milliseconds by default. There is still and option to use microseconds.

2019-01-29 13:47 UTC, lesnitsky commented
@synw good point. I'd actually change it to default option and leave a possibility to use microseconds if needed

2019-01-29 14:38 UTC, synw commented
Yes this is what I did: you can do `PerfTimer.useMilliseconds = false;` to use microseconds. Maybe you mean changing the variable name to `PerfTimer.useMicroseconds`?

2019-01-29 14:40 UTC, lesnitsky commented
exactly. "enabling" smth is better than "disabling" :)

On Tue, Jan 29, 2019, 5:38 PM synw <notifications@github.com wrote:

> Yes this is what I did: you can do PerfTimer.useMilliseconds = false; to
> use microseconds. Maybe you mean changing the variable name to
> PerfTimer.useMicroseconds?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/lesnitsky/perf_timer/pull/1#issuecomment-458563199>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AF-KNkHmuTwekQ-czQfC1Jvs-L4-QrVoks5vIFzpgaJpZM4aU1yi>
> .
>

2019-01-29 15:01 UTC, synw commented
Done

2019-01-30 15:28 UTC, lesnitsky commented on lib/perf_timer.dart
> +      if (useMicroseconds == false) {
`if (!useMicroseconds)`

2019-01-30 15:28 UTC, lesnitsky requested changes
no need to explicitly compare with boolean

2019-01-30 17:48 UTC, synw commented
It's my "explicit is better than implicit" python bias

I changed it  to use the ternary operator for checks, which I guess is more 'dartonic' and elegant

2019-02-01 16:36 UTC, lesnitsky approved these changes

2019-02-01 16:36 UTC, merged